### ISSUE TITLE
Version 7 roadmap (tracking issue)

### ISSUE THREAD

**Issue by KillyMXI** [html-to-text/node-html-to-text#222]
Some improvements I wanted to make will take a while to complete. At the same time there is a growing number of dependency updates, and another LTS Node version is soon to reach the end of support.

Goals for the version 7:

* [x] Node version >= 10.23.2
* [x] Bump dependencies
    * [x] #220 in particular
* [x] Make use of the version bump with minor refactoring
    * [x] Can probably get rid of lodash dependency here and close #221
* [x] Options object pattern for BlockTextBuilder methods, deprecate current positional arguments
* [x] Update docs
    * [x] Changelog
    * [x] Readme
* [x] Update package version and publish

Hopefully this won't take long but it requires the major version bump.

Considered and decided not to include this time:

* #215 - no quick solution, will probably be solved as a part of a bigger work;
* Console warnings for deprecated options - causes some difficulties as long as the CLI is within the package. I will rather focus on moving it out than working around it here.

**Comment by KillyMXI** [comment]
Version 7.0.0 is live!
