### ISSUE TITLE
Version 8 roadmap (tracking issue)

### ISSUE THREAD

**Issue by KillyMXI** [html-to-text/node-html-to-text#228]
### Goals

* Selectors support, to address the biggest user requests;
* When implemented it, I also figured how to improve the weird base elements selection feature (some [breaking changes](https://github.com/html-to-text/node-html-to-text/blob/master/CHANGELOG.md) but hopefully it makes more sense now);
* Introduce `compile` and `convert` functions (an attempt to gain back some performance in batch processing jobs).

### Related issues and PRs

* #159
* #179
* #143 (partly)
* #96
* #215
* #186

### Checklist

* [x] develop a suitable selectors parser ([parseley](https://github.com/mxxii/parseley));
* [x] develop a selectors decision tree ([selderee](https://github.com/mxxii/selderee));
* [x] code changes in `html-to-text`;
* [x] deprecated options handling, tests, documentation, ...;
* [x] push the changes to the repo (selectors branch);
* [x] collect initial feedback;
* [x] publish if everything is fine (probably in a week)
    * [x] update version in package.json and changelog;
    * [x] bump dependencies and regenerate package-lock.json;
    * [x] publish the package;
* [x] collect post-launch feedback.

### Looking for feedback

(I'm no longer highlighting this issue. But if you wish I'm still happy to hear any feedback - in comments here or as a separate issue.)

#### Performance

In case you can benchmark the batch processing time on a large enough practical dataset, I am curious how it differs between 7.1.1 and 8.0.0.

#### Anything unclear

Let me know if you find any changes in configuration and documentation confusing (weird configuration format, weird defaults, unclear instructions, whatever).

#### Web bundlers experience

Works out of the box / needs a workaround, configuration tweaking / etc; with what framework/bundler version...
It would be helpful to map out this area before I dig into it myself and can provide the support outside of Node environment.

**Comment by Niek** [comment]
Wow, that's a lot of changes (and work involved), great job! :) I will do some tests on my codebase shortly and report my findings here.

**Comment by rootwork** [comment]
This is working great for me. I'm using it on [MJML](https://github.com/mjmlio/mjml) to remove the mobile navigation icons (hidden with CSS, but present in the HTML) with the following:

```js
selectors: [{ selector: 'div.mj-menu-trigger', format: 'skip' }],
```

Much cleaner than the regex I was using before.

Thanks for all your hard work making this happen!

**Comment by KillyMXI** [comment]
@Niek Got anything to report?
I'll proceed with the release tomorrow.
If you haven't got around to do anything - no big deal.
It would be a shame if you actually put some effort and it's going to be wasted due to miscommunication.

**Comment by Niek** [comment]
Sorry for the delay @KillyMXI! I tested and can confirm it works *great*! I'm testing with a bunch of (fairly advanced) selector like `blockquote[class^="twitter-tweet"]` and I can skip them properly.
This is much easier than my previous workaround of re-loading the output in JSDom and removing the selectors with a manual loop.

**Comment by KillyMXI** [comment]
Awesome. Thanks everyone.
Version 8 is now live.

**Comment by dargmuesli** [comment]
@webstech would you mind upgrading the type definitions over at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/html-to-text to v8? <3

**Comment by KillyMXI** [comment]
By the way, there is another issue related to type definitions: #223

**Comment by webstech** [comment]
> @webstech would you mind upgrading the type definitions over at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/html-to-text to v8? <3

Working on it.  Wishing I had documented the process better - it was a mix of generated and hand-crafted code.  The typescript code generator is having issues.  Probably something on my end.

**Comment by webstech** [comment]
> Working on it. Wishing I had documented the process better - it was a mix of generated and hand-crafted code. The typescript code generator is having issues. Probably something on my end.

PR [53812](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53812) has been opened.  There is a commit for the v7 changes and another for v8.  Deprecated code is still supported so there should be no breaking changes.

Thanks for bringing this to my attention.

**Comment by KillyMXI** [comment]
All in all, this was quite a quiet release.
Still some great things have happened.
Thanks everyone who helped to bring `@types/html-to-text` up to date.
The package also got a mention in JavaScriptDaily.

Time to close this issue. (That doesn't mean I stop listening for feedback though.)

**Comment by dargmuesli** [comment]
Thanks for your dedicated work!

**Comment by webstech** [comment]
> The package also got a mention in JavaScriptDaily.

Do you have a link for this?  My searches did not go well.  Thanks.

**Comment by Niek** [comment]
> > The package also got a mention in JavaScriptDaily.
> 
> Do you have a link for this? My searches did not go well. Thanks.

https://twitter.com/JavaScriptDaily/status/1402980878230376449?s=20
