### ISSUE TITLE
Version 9 roadmap (tracking issue)

### ISSUE THREAD

**Issue by KillyMXI** [html-to-text/node-html-to-text#240]
~~Work is being done in v9 branch~~.
Version 9 is shipped. [Changelog](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-text/CHANGELOG.md)

### Checklist

- [x] Node ~~12~~ 14 is the minimal supported version
    - [x] Bump dependencies
      - [x] `parseley` and `selderee` are pure TypeScript dual-mode packages, no legacy dependencies anymore
      - [x] Revisit before release
- [x] ES Modules
    - [x] Use ES module syntax in sources
    - [x] Produce both ESM and CJS exports
- [x] Remove `he` module dependency
- [x] Drop options deprecated in v6
- [x] Drop `fromString` (deprecated in v6)
- [x] Drop positional arguments in `BlockTextBuilder` methods (deprecated in v7)
- [x] Drop supplied CLI
    - [x] Middleware that allows better support of modern options - [aspargvs](https://github.com/mxxii/aspargvs)
    - [x] Publish middleware (somewhere close to release date)
    - [x] External CLI package
- [x] #238
- [x] Move generic formatters to base package and make available from any implementation package
    - [x] Solves #231
- [x] Bump date in license file
- [x] Update docs
- [x] Update package links

### Left for later release

- [x] (Sponsored)
    - [x] Split into two packages - base layer and formatters layer (formatters layer will have exactly the same API as the current package - no user-facing differences from this refactoring)
    - [x] Allow to specify character escape sequences (when output format has special meaning for certain characters)
    - [x] Allow to prevent wrapping (as a state, lasting between multiple builder calls)
    - [x] Ability to provide metadata along with HTML document for use in formatters (URL replace in particular)
    - [x] Introduce a companion package "html to markdown" - formatters layer optimized to produce Markdown text of different flavors
    - [ ] Publish the new package (blocker - HTML cleanup)
- [ ] HTML cleanup
    - [ ] Introduce HTML transformers package
    - [ ] Expose HTML transformers package options in -text/md packages options
    - [ ] Provide some default transformers for markdown package to address common issues (valid HTML that doesn't translate into valid Markdown directly)
- [ ] Further docs rework
- [ ] Update issue templates

**Comment by KillyMXI** [comment]
While the work is being delayed, Node 12 is reaching it's end of life: https://nodejs.org/en/about/releases/

If I were confident about the release being close I would've stick to Node 12 anyway.
But it will most likely make no sense when I will finally be able to dedicate my time to finish this.

So the release will likely be targeted for Node 14 and it is at best a couple months away.

**Comment by dargmuesli** [comment]
Hey @KillyMXI, thank you for your great work! Do you think you could publish the v9 alpha to npm as a prerelease so that I can test it?

**Comment by KillyMXI** [comment]
Yes, I thought I'd need to publish a preview to see how the recent changes would work with webpack in particular.
Currently busy with a job, will get to this as soon as I can.

**Comment by KillyMXI** [comment]
@dargmuesli, v9 preview version is live:

`npm i html-to-text@preview`

**Comment by dargmuesli** [comment]
It does work for me! Thank you @KillyMXI :heart:

**Comment by KillyMXI** [comment]
I have a non-code issue I have to deal with during and after v9 release.

I opened a discussion for it:

* #261

Looking forward for any feedback.

**Comment by KillyMXI** [comment]
Version 9 is live.
And new CLI is live.

I hope I didn't miss something.
I won't be surprised there are more issues with CLI I didn't notice. I wonder whether there is a solution for `stdin` not being passed through `.ps1` wrapper in PowerShell.

Now looking for feedback - whether everything works or not.

**Comment by dargmuesli** [comment]
I've upgraded and everything continues to work.
